name: face-detection-app
dependencies:
  - python=3.6
  - pip
  - pip:
    - flask==1.1.1
    - gunicorn==19.9.0
    - opencv-contrib-python==4.1.1.26
    - numpy==1.17.2
    - jupyter==1.0.0
    - matplotlib==3.1.1